### ISSUE TITLE
Indicate Units Somewhere in Traffic Light Rules

### ISSUE THREAD

**Issue by jamesdoyle21** [asascience/ott-coops#112]
When creating new rules in the traffic light tool it isn't obvious what the units are for the bounds. I know they are in the legend but navigating back and forth seems unnecessary - especially when the user is adding several rules at a time.

![image](https://user-images.githubusercontent.com/82955395/134399822-ce0260ed-8cb2-42a1-8055-a3af5f78754a.png)

**Comment by jamesdoyle21** [comment]
Need to do this inside the layer settings page too

![image](https://user-images.githubusercontent.com/82955395/141834816-ecd850b3-1cb1-446b-85c3-32f61833b59a.png)

**Comment by jamesdoyle21** [comment]
This looks good, but noticed a few things while testing, so I put this back into in progress.

- The wind data layers do not have units shown in the same place as the other layers. I know the elevation dropdown shows units, but we want them in the high and low input boxes for consistency
- Units not showing in traffic light section of settings drawer

![image](https://user-images.githubusercontent.com/82955395/142052432-83fdfa57-c0bb-4b43-93ec-3ea528d18995.png)

![image](https://user-images.githubusercontent.com/82955395/142052552-445359de-f1ea-41a2-958c-b31fe028a6f3.png)

**Comment by jamesdoyle21** [comment]
The wind layer not having units showing up is also making it difficult to read the thumbnail rules. This should be fixed when units are added to wind as the other layers look good in this view

![image](https://user-images.githubusercontent.com/82955395/142234753-ffa66092-e718-48eb-a77f-301608f0d603.png)

**Comment by nguyandy** [comment]
The Wind layer not having units is a toughie, I'm still trying to figure this out.

[Let's use the HAWAII wind as an example.](https://eds.ioos.us/thredds/dodsC/ioos/nam/hawaii/Best.html)

The ID we're using for Wind Velocity is `u-component_of_wind_height_above_ground:v-component_of_wind_height_above_ground-group`

Which is a combination of the two variable `u-component_of_wind_height_above_ground` and `v-component_of_wind_height_above_ground-group` These variables independently have the unit name "m/s"

.
.


The goal is to have this getMetadata request return the unit name
https://eds.ioos.us/wms/?REQUEST=GetMetadata&ITEM=layerDetails&LAYERNAME=NAM_HAWAII/u-component_of_wind_height_above_ground:v-component_of_wind_height_above_ground-group

But when we request the metadata for `u-component_of_wind_height_above_ground:v-component_of_wind_height_above_ground-group` it comes back blank - [while individual variable request will return "m/s" ](https://eds.ioos.us/wms/?REQUEST=GetMetadata&ITEM=layerDetails&LAYERNAME=NAM_HAWAII/u-component_of_wind_height_above_ground)

I tried updating the NAM_HAWAII.ncml file to add this snippet
```
  <variable name="u-component_of_wind_height_above_ground:v-component_of_wind_height_above_ground-group" type="float">
    <attribute name="units" type="String" value="m/s" />
  </variable>
```

But that didn't do anything lol, but it's most likely because I'm doing something wrong. 
Not sure if this requires an update in the actual source data.

I really don't want to hack this around to get Wind units to show up properly, would be nice if we can figure out a real solution. 

@mpiannucci any thoughts?

**Comment by mpiannucci** [comment]
for traffic lights, vector groups use the magnitude param. So you can do a swap here in the metadata to fetch the data for the magnitude field from `u-component_of_wind_height_above_ground:v-component_of_wind_height_above_ground-group` to `u-component_of_wind_height_above_ground:v-component_of_wind_height_above_ground-mag`

**Comment by nguyandy** [comment]
These issues should be resolved now with the new changes in data-catalog.
<img width="564" alt="Screen Shot 2021-12-01 at 11 03 58 AM" src="https://user-images.githubusercontent.com/43226410/144269313-e3f08a5a-b46e-4e9f-b9f0-5cab49996bee.png">
<img width="562" alt="Screen Shot 2021-12-01 at 11 03 40 AM" src="https://user-images.githubusercontent.com/43226410/144269317-69693a0f-40bd-4c10-9efc-577fed550787.png">
<img width="434" alt="Screen Shot 2021-12-01 at 11 03 33 AM" src="https://user-images.githubusercontent.com/43226410/144269318-6162e551-b190-413d-9367-4ee242365953.png">
