### ISSUE TITLE
Allow User to Edit Opacity for Traffic Light Layers

### ISSUE THREAD

**Issue by jamesdoyle21** [asascience/ott-coops#116]

**Comment by mpiannucci** [comment]
This should be a slider the user can use to toggle the opacity under the layer rules listing: 

![Screen Shot 2021-10-12 at 9 49 32 AM](https://user-images.githubusercontent.com/1832671/136968574-23cb3cb0-380e-4447-a4ad-c5ab96bfe513.png)
 
To get to this point, first Click the Traffic Light icon in the sidebar. Then click "Create Layer". Then Click "Add Rule" and choose "Wave Height @ NOAA Mt Holly......". Leave the defaults, and click "Save".

**Comment by ndellicarpini** [comment]
I wonder if it makes more sense to have a layer settings button for a traffic light layer, similar to how settings work for data layers? As an extension to this, maybe the settings button for each layer should be in the active layers pane rather than in the traffic light layer / data layer panes.

Just a suggestion, looking forward to any responses you guys have.

**Comment by mpiannucci** [comment]
Maybe. For now, lets leave this issue for a later time. I am trying to think about the layer API and how best to manage duplicated settings stuff

**Comment by jamesdoyle21** [comment]
You're saying to essentially bring the settings functionality from the data layers to the traffic light layers and have a gear icon here that opens it? Not a bad idea, if we need all the same functionality for traffic light layers. Lets discuss in the next meeting

![image](https://user-images.githubusercontent.com/82955395/137761780-b6fc80c6-a45c-4eef-98c2-f89745b01c3f.png)

**Comment by mpiannucci** [comment]
All we really need is opacity though so might be overkill to have a whole menu to show for that

**Comment by ndellicarpini** [comment]
Yea, I didn't know if we would be adding any other features from the data layer's settings page to traffic light layers. If it's just opacity it probably makes sense to not create another submenu like the data layer settings. 

Also, rather than putting the gear button in the traffic light layer pane, I was thinking we could move all of the gear buttons into the active layer pane, as I believe it could be reasonably assumed that a user would only care to edit the settings of an active layer. Additionally, this would move all of the layer settings into one place.

Regardless, for now I am going to add the opacity slider as proposed in the original issue.

**Comment by mpiannucci** [comment]
> Also, rather than putting the gear button in the traffic light layer pane, I was thinking we could move all of the gear buttons into the active layer pane, as I believe it could be reasonably assumed that a user would only care to edit the settings of an active layer. Additionally, this would move all of the layer settings into one place.

Ideally the settings would be in both places, which we will work towards soon.

**Comment by ndellicarpini** [comment]
I added the opacity slider here https://github.com/asascience/oceansmap-3/commit/1b239bb7e9215526155cc28e922ce42cb59f8f68

I only added very basic styling for the slider. It seems to me like the Traffic Light Layer pane will probably get more styling in the future, so it might end up being more cohesive if the opacity slider styling is done at the same time as the general traffic layer styling. 

Please let me know if my assumptions are wrong and I can add additional styling to the opacity slider. Thanks for the help on this issue.

**Comment by ndellicarpini** [comment]
PR: https://github.com/asascience/oceansmap-3/pull/99

**Comment by ndellicarpini** [comment]
Move to edit traffic layer pane

**Comment by jamesdoyle21** [comment]
Talked today about putting this inside the Traffic light layer settings

![image](https://user-images.githubusercontent.com/82955395/140816029-4e76153a-5edd-4e4f-939f-35dcc4d6f29a.png)

**Comment by ndellicarpini** [comment]
PR: https://github.com/asascience/oceansmap-3/pull/114
