### ISSUE TITLE
Think About how to Create a Time-Based Traffic Light Tool

### ISSUE THREAD

**Issue by jamesdoyle21** [asascience/ott-coops#117]
For example, workers want to know when they can service an offshore wind turbine when waves and wind are low. They have the exact coordinates of the turbine, so the spatial data layer is not very useful, but if they could see a green/red indicator throughout some range of time, that would be useful.

**Comment by jamesdoyle21** [comment]
This relates to how FMIS uses the bottom drawer time series plotted with the traffic light colors as the background of the plot

**Comment by jamesdoyle21** [comment]
Potential next enhancement

**Comment by kvmartin001** [comment]
This would be a fun one that I could tackle.

Major parts as I see them:
- Need a UI for rule creation -> "Generate Timeline" button combines rules with the result of multiple getTimeseries requests to calculate threshold points on a `TimeSlider`-like display
  - There might be more than two threshold points unlike spatial traffic light layers - conditions could flip flop back and forth along the timeline
- Need data structure for storing these "traffic light timelines"
- Need a new component to display these colored timelines (not sure where, maybe a new tabbed section of the Obs Drawer)
- The user could access this tool from a new button in the Observation Drawer

Questions:
- What happens if layers have no data at the selected point, or have gaps in data across the selected time range?
- How would this handle different lengths of timesteps between layers?

**Comment by jamesdoyle21** [comment]
For times when any of the layers in the traffic light rules has no data, we would probably want a 4th color, dark gray perhaps, and add a tooltip when the user hovers over that particular time on the slider with a warning saying X data layer has no data at Y time

As for the different lengths of timesteps, what could be the biggest difference in time here? We could set it so that in order for the selected time to be green, the data at the timestep before and after that selected time for all rules must meet the criteria. Otherwise it shows yellow / red.

**Comment by kvmartin001** [comment]
> As for the different lengths of timesteps, what could be the biggest difference in time here?

On second thought, the problem of data gaps and timestep differences is basically the same. Many layers update every hour, but some only update a few times a day and some have multi-day gaps surrounding just a few data points.

There will probably be a singular out-of-date cutoff for all layers. The timeline will turn gray if any of the layers have gone out-of-date at that point, and will return to normal at the next point where all layers are considered valid.

**Comment by mpiannucci** [comment]
Closing in favor of one ticket: https://github.com/asascience/ott-coops/issues/447
