### ISSUE TITLE
Remove Second Y Axis when Viewing Observation Data at a Station

### ISSUE THREAD

**Issue by jamesdoyle21** [asascience/ott-coops#125]

**Comment by mpiannucci** [comment]
This ticket is incorrectly worded. The actual issue is that when the observation view is being used, if two variables have the same parameter, they should share an axis..

So for example, wave height from a buoy should share an axis with wave height from a model, but not with a wind model or wind observation field

**Comment by jamesdoyle21** [comment]
![image](https://user-images.githubusercontent.com/82955395/135882792-0ef68d73-be49-48cb-89cc-e5b0e64c8b4d.png)

**Comment by jamesdoyle21** [comment]
Notice the different scales in the example above
