### ISSUE TITLE
Ensure "Active" and "View Bounds" Buttons in Data Layers are Highlighted when Appropriate

### ISSUE THREAD

**Issue by jamesdoyle21** [asascience/ott-coops#133]
https://user-images.githubusercontent.com/82955395/137035551-b02d3bcd-33d8-47fa-9db3-7042ed053c92.mp4

As seen in this video, when switching clicks between "Active" and "View Bounds" only 1 will be highlighted blue at a time. The user can use both to show active layers within the bounds of the map view, and when they do, both buttons should be highlighted

**Comment by ndellicarpini** [comment]
So this is happening at the useEffect ObservationDrawer.tsx:163. I have pushed a very simple fix to https://github.com/asascience/oceansmap-3/commit/5988681ca5bb8b1f135f6ccf26c1de296d99dfca
(this just checks if the drawer is open before updating the elevation on the plot)

However, this changes the functionality, now if you change the elevation slider with the drawer closed, the drawer does not reopen. A better change could be to hide the elevation slider when its not appropriate rather than removing it, which would maintain the currentElevation between activations of elevation slider.

I am open to either my current fix or the fix I described above, just let me know and I'll set up a pr for either.

**Comment by jamesdoyle21** [comment]
@ndellicarpini are you referring to issue #131 ?

**Comment by ndellicarpini** [comment]
> @ndellicarpini are you referring to issue #131 ?

yes I am, sorry my mistake

**Comment by ndellicarpini** [comment]
Should the functionality of the buttons be changed as well? Currently the buttons do not act as toggles, when you press it the filter is on until you press the `Reset` button. With this highlighting change, would it make sense to also set the buttons to act as toggles, so that when you press a filter button when the filter is on, it would un-highlight the button and turn off the filter.

**Comment by mpiannucci** [comment]
yes thats correct

**Comment by ndellicarpini** [comment]
PR: https://github.com/asascience/oceansmap-3/pull/108
