### ISSUE TITLE
Add Support for Specifying and Switching Unit Systems 

### ISSUE THREAD

**Issue by mpiannucci** [asascience/ott-coops#139]

**Comment by mpiannucci** [comment]
Related #112

**Comment by mpiannucci** [comment]
All units stuff in OM1 is handled in the python layer relying on [udunits](https://github.com/Unidata/UDUNITS-2) api. There is not port of this to JS, there is an alternative package found by @nguyandy [here](https://www.npmjs.com/package/convert-units) but this creates a mismatch because data-catalog gets the units from udunits so even more work would be needed to translate parameter names. 

So the options going forward are as follows: 

1. Use convert-units node package and translate all the names and try to fill what is missing (dont like this much)
2. Rewrite udunits port to js, keeping as thin as possible. (not an insignificant effort)
3. Package udunits for wasm and us the API that way (would require emscripten and custom build scripts. emscripten creates an impact on bundle size)
4. Create a unit conversion API in the python proxy layer and use that api every time a unit needs to be converted. (potentially heavy perf impact when the user is using non default units). 

I am leaning towards option 3 in order to keep perf as good as possible and to minimize long term impacts of maintaining a large multi-thousand line js codebase full of units, but value any input from others

**Comment by nguyandy** [comment]
I'm not familiar with enscripten so can't comment on the level of effort w/ that.

I think option #4 can get messy when we're dealing with plots since that's a lot of data points to convert = a lot of requests to the python proxy layer.


But to iterate on option #1, I don't think it'll be multi-thousand lines.
We can take advantage of these mapped parameters/aliases, add an id along with each parameter. 
https://github.com/asascience/oceansmap-3/blob/master/frontend/src/components/ValidationTool/ValidationTool.tsx#L21

And then with those mapped params/ids, we can build something like the OM1 units.py, but with convert_units
https://github.com/asascience/OceansMap/blob/master/oceansmap/units.py

fwiw, we are already dealing with unit mismatch when we make GFI requests, translating the units should be pretty simple map. Already have a similar unit mapping function w/ the profile plot update

``` 
export function prettyUnits(units: string): string {
    units = units.toLowerCase();

    const map = {
        "degrees in celcius": "°C",
        "degrees_celsius": "°C",
        "degc": "°C",
        "degrees_c": "°C",
        "deg_c": "°C",
        "celsius": "°C",
        "degrees": "°",
        "degrees_true": "°",
        "directionto angles in degrees": "°",
        "degrees_north": "°N",
        "degrees_east": "°E",
        "knots": "kt",
        "mg_chl/m3": "mg chl/m³",
        "meters": "m",
        "m3/s": "m³/s"
    }
    if (map.hasOwnProperty(units)) {
        return map[units];
    }
    return units;
}
```

But agreed, convert-units library isn't as extensive as udunits, we'd have to write some conversions ourselves and that's a big bummer.

**Comment by mpiannucci** [comment]
Thanks for the detailed write up andy. It does look like `convert-units` has a pretty good API for extending measures and we would just have to make sure we document and wrap everything nicely if we go that way. 

I will prob spend a short amount of effort seeing what emscripten gives us (just because it gives us 100% coverage on udunits immediately if it works), but I think using and extending convert-units library to cover what we need might be best if emscripten is too hard.

**Comment by mpiannucci** [comment]
So I spent some time working on this today. I think that we should probbaly go the way of updating and extending the `convert-units` package for our use cases (hopefully just defining custom units and aliases as needed)

**Comment by mpiannucci** [comment]
During demo, Salinity is failing with unit PSU unsupported

**Comment by nguyandy** [comment]
Do we want to convert PSU? Or just leave it as is between the unit systems?

Did some googling, found this and didn't find a unit that PSU is converted to.
But since its in metric ratios, I guess theres a possibility to convert it to imperial ratios? - just not sure if that's practical.

from googling
`Ocean salinity is generally defined as the salt concentration (e.g., Sodium and Chlorure) in sea water.  It is measured in unit of PSU (Practical Salinity Unit), which is a unit based on the properties of sea water conductivity. It is equivalent to per thousand or (o/00) or to  g/kg.`

**Comment by jamesdoyle21** [comment]
Did some googling as well and even though they give it the unique name of PSU, it looks like we don't need to convert anything since PSU is just parts per thousand

**Comment by jamesdoyle21** [comment]
Areas that need updating:

- 3D vertical slider
- Elevation in active layer legends tool
- Elevation in traffic light tool
- NOAA West Coast (WCOFS) no salinity units given
- No wind units given in settings tab
- Air temperature is in Kelvin
- Air pressure only given in Pascals in layer settings tab. Needs to be PSI for imperial. (Should this be bar instead of pascals for metric? Future discussion)
- Validation Tool?

**Comment by nguyandy** [comment]
> Areas that need updating:
> 
> * 3D vertical slider
> * Elevation in active layer legends tool
> * Elevation in traffic light tool
> * NOAA West Coast (WCOFS) no salinity units given
> * No wind units given in settings tab
> * Air temperature is in Kelvin
> * Air pressure only given in Pascals in layer settings tab. Needs to be PSI for imperial. (Should this be bar instead of pascals for metric? Future discussion)
> * Validation Tool?

Thanks for the list James, only seeing this now. There's a few here that I missed in the merge today, I'll get these sorted out.

**Comment by jamesdoyle21** [comment]
@nguyandy This is close, but the elevation in the traffic light tool is still not updating

![image](https://user-images.githubusercontent.com/82955395/145465126-9267c5a5-5764-4b45-b9be-14926bace409.png)

**Comment by jamesdoyle21** [comment]
Also, the air temperature is in Kelvin still. I assume we want to be consistent with water temperature and use C and F. Everything else on that list looks good though

**Comment by nguyandy** [comment]
> Also, the air temperature is in Kelvin still. I assume we want to be consistent with water temperature and use C and F. 

Ah yea that's an update we need to make w/ the data.

@patrick-tripp, can you update the "Temperature_surface" for GFS Global to use degC for units? 
The values seem to be scaled to celsius, just returning K as the unit. 

I see there's a snippet in the `GFS.ncml` file for this, unsure why that's not working though.
```
  <variable name="Temperature_surface">
    <attribute name="units"  value="degC" />
    <attribute name="add_offset" type="float" value="-273.15" />
    <attribute name="scale_factor" type="float" value="1" />
  </variable>
```
