### ISSUE TITLE
Determine Why "Atlantic Wave Height" is not an Option in Validation Tool

### ISSUE THREAD

**Issue by jamesdoyle21** [asascience/ott-coops#140]
For some reason, Atlantic Wave Height sometimes does not show as a Comparison option for the Validation Tool. When the user selects "Wave Height" as the Parameter, Atlantic Wave Height should be an option for the Comparison as long as the station selected is within the bounds of atlantic wave height (which is big) Stations 44008 and 44097 are examples.

There may be other bugs here with certain layers showing up here or not, Atlantic Wave Height is just the one I noticed because its the layer I like to use for testing. Additional testing with the Validation Tool should be done to determine this.

![image](https://user-images.githubusercontent.com/82955395/137738312-4d2f48ee-70c0-476e-a6d0-a665c557e30a.png)

**Comment by ndellicarpini** [comment]
I have not been able to recreate this, do you remember what steps you went through in your testing to produce this?

**Comment by jamesdoyle21** [comment]
https://user-images.githubusercontent.com/82955395/137970647-593a4d0d-8c20-4c2d-bae8-f15e04486adc.mp4

Here's one example

**Comment by jamesdoyle21** [comment]
https://user-images.githubusercontent.com/82955395/137970774-f1ec6588-9181-45aa-a33a-8ad80d570d99.mp4

Here's another. I can't get Atlantic Wave Height to show up at all

**Comment by ndellicarpini** [comment]
https://user-images.githubusercontent.com/22432482/137973096-2f077a4a-ca5f-43b7-9d57-24188d30a903.mp4

https://user-images.githubusercontent.com/22432482/137973143-fbf153b6-6a84-4690-a3f1-8afdc110b441.mp4

Interesting

**Comment by jamesdoyle21** [comment]
@mpiannucci @nguyandy you guys see this? Atlantic Wave Height coming up for Nick but not me

**Comment by mpiannucci** [comment]
yeah idk what is going on with this. it makes no sense

**Comment by nguyandy** [comment]
It's not showing up for me either
<img width="487" alt="Screen Shot 2021-10-19 at 3 46 17 PM" src="https://user-images.githubusercontent.com/43226410/137979998-4ccb8b80-1ec7-4cc8-95e9-54de2ffc35aa.png">

**Comment by ndellicarpini** [comment]
wait so am I the only person that can see Atlantic in the comparison list?

**Comment by mpiannucci** [comment]
I can see it when im running locally on master but cant see it on the demo site haha... very weird

**Comment by mpiannucci** [comment]
To note: This works locally but not on deployed site.

it also shows correctly if the layer in question has been selected in the layerlist before going to validation tab

**Comment by ndellicarpini** [comment]
I've noticed a discrepancy in the execution of development vs production. In development, `findAvailableModels` is called twice for every change in the validation tool's selected parameters, while in production it is only called once.

In the pictures linked, the collapsed arrays (`ValidationTool.tsx:170`) are the available Comparisons. In development, once the Parameter & Station (`ValidationTool.tsx:169`) are selected, the array of Comparisons only has 2 members, and the second call of `findAvailableModels` shows the Comparisons array having 3 members. In production, `findAvailableModels` is only called once, and the single Comparisons array print only shows 2 members.

DEVELOPMENT
![live](https://user-images.githubusercontent.com/22432482/139926782-f787e438-6546-4fe6-9001-903d07c69177.png)

PRODUCTION
![prod](https://user-images.githubusercontent.com/22432482/139926819-dc619533-d54d-4519-b3d6-a76e0a2ea9a0.png)

Yes this missing member is the Atlantic Wave Height. I'm currently looking into why, but I figured I'd info dump here in case anyone knew why the execution is different between development & production.

EDIT: Turns out the "being called twice" thing in development is intended, I guess the bigger question then is why is Atlantic not there on the first call.

**Comment by ndellicarpini** [comment]
i guess its intended behavior? https://github.com/facebook/react/issues/17186

**Comment by ndellicarpini** [comment]
PR: https://github.com/asascience/oceansmap-3/pull/110

This is mostly speculation, but this PR seemed to fix the issue regardless of if my understanding is 100% accurate. Previously, values were being reversed using the function `.reverse()` which actually works in-place. This becomes an issue because the value being reversed in-place is actually stateful, so the reversed part of the value is saved to the state. This probably caused all sorts of weirdness, which might have worked in development because of the aforementioned double rendering thing, but would break in production.
