### ISSUE TITLE
Validation Tool - All 4 Inputs Selected, No Response

### ISSUE THREAD

**Issue by jamesdoyle21** [asascience/ott-coops#142]
Sometimes for the validation tool I select all 4 inputs and nothing loads. If there is an error, or no data or something going on we should show that. Otherwise the user is going to wait around for nothing or refresh the page

![image](https://user-images.githubusercontent.com/82955395/137742596-a3e081db-a9a6-4ede-8215-5ab36f4254ba.png)

**Comment by mpiannucci** [comment]
This means there was an error fetching from the API. Show user that there was an error instead of showing nothing.

**Comment by mpiannucci** [comment]
@ndellicarpini just adding more to your backlog. This bug is just that when there is a failure in fetching the validation data, the error is logged but nothing is shown to the user in the UI. 

So this ticket is for showing an error message in the UI so the user knows there was an error, and a button to trigger the validation to try again.

**Comment by ndellicarpini** [comment]
Alright here is a solution: https://github.com/asascience/oceansmap-3/tree/nick-validation-error-msg

I don't know if the retry button fully works due to the server being difficult today, but I'm interested in what you guys think about the design of my error message/button. I'm not entirely convinced of them myself, but I'm interested in hearing other opinions.
![nohover](https://user-images.githubusercontent.com/22432482/139729901-d2623538-301b-4692-9f68-47ac4c7afc92.png)  

Mouse onHover
![hover](https://user-images.githubusercontent.com/22432482/139729913-f3f8d2f8-ed5a-4900-9d5c-e8671a204705.png)

**Comment by mpiannucci** [comment]
Looks good to me. @jamesdoyle21 what do you think of appearance

**Comment by jamesdoyle21** [comment]
@ndellicarpini @mpiannucci I think this looks good. Neither are visible until an error occurs, correct? If we find there are situations where we can provide more info into what the error actually is, that could be useful. But for now, this is good.

**Comment by ndellicarpini** [comment]
@jamesdoyle21 Yes this only appears when the chart fails to load, appearing where the chart was supposed to be loaded. Also I could add further error details by doing some formatting on the error message, but I'm not sure if there could be errors where the message is like a whole stack trace or something (although to be clear I haven't seen any like this).

**Comment by jamesdoyle21** [comment]
Cool, this is all we need for now. Nice work

**Comment by ndellicarpini** [comment]
PR: https://github.com/asascience/oceansmap-3/pull/109

NOTE: I still haven't tested if I haven't broken the chart loading regularly because the server is not working, will ask for pr review once I can verify all validation functionality.

NOTE 2: I have tested it and now it works
