### ISSUE TITLE
Add Privacy Policy, Contact Us, and About Inside Hamburger on the Top Right

### ISSUE THREAD

**Issue by jamesdoyle21** [asascience/ott-coops#150]
Same as MARACOOS version

**Comment by mpiannucci** [comment]
Alright so quick point on the design of the Tools for contact us and privacy policy. Both of these might be common components for different deployments but will probably have differing people to be contacts or differing privacy policies. 

Because of this, the Tools for privacy policy and contact us should accept probs in a builder like fashion so they can be configured in the config file for each deployment. 

For example in the tool: 

```typescript
const MyPrivacyPolicyTool = ({privacyPolicyUrl}: {privacyPolicyUrl: string}) => {
    return () => (
        <div>
             {privacyPolicyUrl}
        </div>
    )
};
```

and then used in the privacy policy with..

```typescript
    tools: [
        MyPrivacyPolicyTool({privacyPolicyUrl: 'oceansmap.com/privacy'}),
    ],
```

**Comment by mpiannucci** [comment]
As for sending emails, here is the relevant code for OM1: https://github.com/asascience/OceansMap/blob/master/oceansmap/oceansmap_email.py

As you can see it is using flask_mail to send the email. We are not using flask, so we need to find an alternative solution to this. We are using a web framework called starlette for the backend, which is pretty low level so there are two options for this: 

1. We do it with pure python, but this presents issues with configuration. if we just use generic OM creds its fine, but not sure if thats true, need to look more into OM1. 
2. We do it with node when we switch to use next.js so it can be packed into the configuration files. 

Lets focus on UI and privacy policy first and circle back on email next week.
