### ISSUE TITLE
Mega Big Logo Bug - Screenshot Tool

### ISSUE THREAD

**Issue by jamesdoyle21** [asascience/ott-coops#152]
![image](https://user-images.githubusercontent.com/82955395/138942601-0b61dcf6-c2d5-4d7f-af5d-1a702d89c08a.png)

**Comment by ndellicarpini** [comment]
Oh man, I thought this was assigned to me because me and andy's icons are so similar oops. Anyhow while I was looking into this issue, I noticed that if the browser window was taller than it was wide (like on a phone), the map would almost always end up on a second page. Is this a problem worth looking into, or is a solution like user defined sizing & placement for screenshot elements something that is being planned for the future?

**Comment by nguyandy** [comment]
#twinning

Nice find @ndellicarpini.
An easy fix for now would be to set the screenshot image max height to a fixed ratio like 70% so that it doesn't end up on a second page.

A better approach would be to check the screenshot size ratio. If the screenshot is taller than wide, we set the print page orientation to portrait mode, else keep it as landscape mode. (and keeping the screenshot image max height to a fixed % of the page)

There are plans to allow users to customize and configure their screenshot, but in terms of sizing and placement, it might be easier for us to handle it on our end for now. 

Thoughts @jamesdoyle21 @mpiannucci ?

**Comment by jamesdoyle21** [comment]
That all sounds reasonable to me

**Comment by jamesdoyle21** [comment]
Also, @ndellicarpini @nguyandy at least one of you should change your icon on here so we don't get mixed up again. The same thing happens to me when I am trying to see which of you is assigned to a task
