### ISSUE TITLE
Quick Adding Virtual Stations while a Data Layer is loading will cause lag

### ISSUE THREAD

**Issue by ndellicarpini** [asascience/ott-coops#162]
If you `Quick add multiple stations` while a data layer is loading in the background, the entire site seems to have random lag. 

Some examples of this lag:
- the virtual station icons will take 30s+ to load
- the data layer will take much longer to load than normal
- mouse over highlighting of the data layer list will lag behind the actual mouse position

Also, the mouse over highlighting lag seems to even stay after a page hard refresh? I don't understand how this could happen (maybe specific to developer mode?)

**Comment by mpiannucci** [comment]
Yeha quick adding while doing anything absolutely wrecks performance

**Comment by nguyandy** [comment]
@mpiannucci did your update fix the lag issue here?

We could always go back to using SDFs instead of loading the mapbox markers.
It'll look uggo, but should perform a lot faster since we don't need to fetch marker icons.

**Comment by mpiannucci** [comment]
No it leaves it the same I think. I just added Promise stuff to the marker loading but it made it worse so I will probbaly mess with SDFs this week.. good idea

**Comment by kvmartin001** [comment]
In Leaflet I've used raw SVG code to make recolorable pattern fills. I'd imagine you could do the same for marker images, and you wouldn't have to fetch an asset.
The [mapbox GL docs](https://docs.mapbox.com/help/troubleshooting/using-recolorable-images-in-mapbox-maps/) suggest you can't recolor SVG markers, but I think that might just be for loaded SVG files

**Comment by kvmartin001** [comment]
This still occurs post- permalink addition and permalink fixes.

**Comment by jamesdoyle21** [comment]
I just tested and it seems fast to me. What steps did you take @kvmartin001 ?

**Comment by kvmartin001** [comment]
@jamesdoyle21 
The lag actually doesn't seem as bad as it was before.

https://user-images.githubusercontent.com/56608780/144092409-2a3d329d-82a0-406f-8e24-22a6aa7a4483.mp4

I just noticed something in this recording though. Some of the quickly-added vStations ended up with identical names.
I think all stations that appear after the lag period end up with the same name.

**Comment by ndellicarpini** [comment]
The lag is definitely correlated to how fast the layer loads, as I'm pretty sure the marker lag is just that it waits for the marker image to be fetched before showing the marker on the map / in the list. Now this lag can be exacerbated by how fast the layers load, as it seems like the marker image loading is sometimes 'suspended' for layer tiles to finish loading.

I think the way to fix the lag & naming issue is to somehow detach the marker image loading from adding the vstation to the list/map, although I haven't really looked at it so take that with a grain of salt.

**Comment by mpiannucci** [comment]
> I think the way to fix the lag & naming issue is to somehow detach the marker image loading from adding the vstation to the list/map, although I haven't really looked at it so take that with a grain of salt.

We arent using actual markers for the markers, we are using a geojson source with a symbol layer that renders a given icon. The icon is required to be loaded into the map before it can be rendered to the screen. @nguyandy couldnt get coloring of a single marker image to work right so we are using a hack right now that loads a new marker with a different color for each marker that needs a different color (so the lag makes sense). 

The solution to this is most likely to figure out how to get the marker coloring to work correctly so GL can handle it instead of fetching and loading a million icons while other data is also being fetched.

**Comment by nguyandy** [comment]
I got the SDF colors working, it was just super ugly since the marker was just a solid color.
Definitely didn't realize the lag w/ loaders when there are layers loading back then or else I would've stuck to SDF.

Maybe there's a way to preserve marker shading/shadows so it looks a bit better.

<img width="441" alt="MicrosoftTeams-image (4)" src="https://user-images.githubusercontent.com/43226410/144099847-b1e1adb0-9e0a-4f8c-ad1a-4d4b4eee6e8e.png">

**Comment by mpiannucci** [comment]
> Maybe there's a way to preserve marker shading/shadows so it looks a bit better.

Righhtttt now i remember, thanks for correcting. Yeah so some time should be spent to figure out if we can get better SDF rendering in some way (even with a diff icon if necessary)
