### ISSUE TITLE
Issue when creating a Virtual Station from the Observation Drawer

### ISSUE THREAD

**Issue by nguyandy** [asascience/ott-coops#176]
Steps to reproduce:
1. Enable any layer (in order to open up the observation drawer on map click)
2. Click somewhere on the map
3. Click on the "Add to Virtual Station" button.
<img width="370" alt="Screen Shot 2021-11-10 at 11 10 27 AM" src="https://user-images.githubusercontent.com/43226410/141149698-23f8bf92-e42d-4563-8b27-e16465fc7ffa.png">
4. Click on the Virtual Station tool.

Two problems here.
at step 3, the Virtual station is added to our tool (we see the counter increasing), but the marker is not rendered on the map
at step 4, the app crashes.

For step 3, the marker isn't loading most likely because we didn't load the marker color before rendering the marker.
Check out some examples here
https://github.com/asascience/oceansmap-3/blob/master/frontend/src/components/Map/Map.tsx#L97
https://github.com/asascience/oceansmap-3/blob/master/frontend/src/components/VirtualStationTool/VirtualStationAddEdit.tsx#L77

**Comment by kvmartin001** [comment]
The virtual station is not receiving lat and lon from the mouse click. That seems to be why it crashes.
It is still being added to the list though. I'm going to compare to the Add function from the Add/Edit component because that works.

**Comment by kvmartin001** [comment]
Fixed the crash in step 4. `mapClickEvent` now stores the coordinates inside `lngLat`, so the `addToVirtualStations` function calls just needed to be updated.

The marker still doesn't appear right away. Going into the edit view and clicking Save makes it appear, probably because it needs a random color when it gets added via the Observation Drawer.

**Comment by kvmartin001** [comment]
I've added the step where the mapbox marker image gets loaded (`await loadMarkerColor` as in Andy's example)
Markers still don't appear until I switch to the Add/Edit view, even if I add multiple markers before doing so.

I'm sure the async function is working, since I can add a 3-second delay to the `loadMarkerColor` function and the virtual station does not get created until after the delay.

**Comment by kvmartin001** [comment]
Marker rendering is fixed! The actual mapbox addition/removal code was in the Virtual Station Tool and being exported from there into the Virtual Station Add/Edit Tool. Maybe there should be a Virtual Station Utils file in the future.
