### ISSUE TITLE
Permalink - Save Layer Order

### ISSUE THREAD

**Issue by jamesdoyle21** [asascience/ott-coops#203]
Even when we get to the point where we can manually rearrange the order of layers, it would still be robust if the permalink saved the order of the layers in which they show on the map. 

https://user-images.githubusercontent.com/82955395/144100397-898d3112-8bf8-46da-85a5-d7b6ed0fefe1.mp4

**Comment by ndellicarpini** [comment]
Although this technically doesn't require a real layer priority system, I think it might be easier if I do. My current thought is to convert `selectedCatalogItems` to a map, where the key is the priority of the layer. For things like vector layers, I could have the priorities start at like 1000 or something. I would keep the hard-coded priorities for things like `Map`, `Markers`, and `BoundingBox`. 

This is going to be a little annoying to implement in this way, but I still think creating a real priority system would be a better use of time than trying to add our current priority system to the permalinks. 

I don't know if my approach is the best way to do priorities. @mpiannucci If you have any thoughts on my idea or if you have different ideas, I'd appreciate it.

**Comment by mpiannucci** [comment]
hmmm ill have to think about this one. I probably like storing the layer priorities in a separate container vs using them as the keys themselves to be explicit about it. So like keep the selectedCatalogItems how they are and then make another map that stores the priorities keyed by the layer ids?

**Comment by ndellicarpini** [comment]
Yea I definitely feel similarly. However, the issue with doing it like this is that we'd effectively have 2 lists of the layer ids, which is probably not a good use of space when we're so limited by the permalink 2000 chars.

**Comment by mpiannucci** [comment]
wait is selectedCatalogItems a list? Then we just sort them in the right order prob

**Comment by ndellicarpini** [comment]
Hmm, yea I could try that. I feel like the logic when adding a layer could get annoying, probably requiring the list order to be reset before `map.addLayer` is called, but this could be easier than converting `selectedCatalogItems` to a map.

**Comment by ndellicarpini** [comment]
Ok, so unfortunately I don't think just using `selectedCatalogItems` is going to work, as things like coastlines & traffic layers aren't and shouldn't be in the `selectedCatalogItems` list. I think my plan of attack is going to be a separate sorted list of all layers put into their correct order. Then, instead of passing `selectedCatalogItems` and `selectedTrafficLightItems` to permalink, I'll just pass the `sortedLayerIDs`, and then I'll try to figure out some parsing to separate the layers between catalog & traffic layers. This will also save the coastline status to permalink, which as far as I can tell isn't currently saved.
