### ISSUE TITLE
Profile Plots dont show on Mobile

### ISSUE THREAD

**Issue by mpiannucci** [asascience/ott-coops#212]
Need to think about UI for mobile, cuz right now profiles dont work on mobile

**Comment by nguyandy** [comment]
How about a tabbed display for the plots inside the drawer - if profile plots are available?

https://ant.design/components/tabs/

Timeseries | Profile

**Comment by jamesdoyle21** [comment]
Are you thinking just mobile with those tabs or desktop too? It is getting a bit busy with profile plots

![image](https://user-images.githubusercontent.com/82955395/144881018-150985bf-5d88-46c3-8edc-e3c2febbb353.png)

**Comment by nguyandy** [comment]
@jamesdoyle21 Was thinking for just mobile.
The profile plot is following the same design as OM1 atm, 
since it's more of a portrait-style plot, it looks a bit odd when we squish it down to fit the timeseries height.

I see what you mean by busy... Ideally users would have the data-layer closed when they're done picking out what they want.

**Comment by nguyandy** [comment]
mockup 

![pro1](https://user-images.githubusercontent.com/43226410/144890527-ca3858a0-f683-4364-8adc-a3edf50e37f7.png)
![pro2](https://user-images.githubusercontent.com/43226410/144890529-f48a18fb-a666-4108-bcd8-1f6d91e64370.png)

**Comment by jamesdoyle21** [comment]
Mockup looks great. And yeah, I don't think a user will ever need all of these windows open at once. It looks fine for now, but something to keep in mind as we add new features

**Comment by mpiannucci** [comment]
I looooveee that for mobile. And we can eventually add tabs for the advanced plottting stuff too
