### ISSUE TITLE
Fix the 2.94 ft Offset when Validating Waterline Data in Delaware Bay

### ISSUE THREAD

**Issue by jamesdoyle21** [asascience/ott-coops#223]
There is a datum error for waterline data of 2.94 ft across the board for waterline layers

![image](https://user-images.githubusercontent.com/82955395/145286800-397f64c9-f5eb-429f-bba5-bfaad654ac38.png)

![image](https://user-images.githubusercontent.com/82955395/145286840-f5caf6c0-b5b4-4521-a778-857e3cf219f3.png)

**Comment by jamesdoyle21** [comment]
@patrick-tripp this appears to be a backend problem. Did we know about this?

**Comment by patrick-tripp** [comment]
Strange. This is the first I’ve heard about this. This is comparing the observation data from a station to the forecast? Or is this from virtual stations? Where is the station data coming from? 
One could check the raw netcdf forecast output at that corresponding point and see if that’s the same value being shown here. I’m not aware of any such bias in the forecast and don’t see how the backend could skew the data like that.

**Comment by jamesdoyle21** [comment]
This is observation data from station 8539094 compared to NOAA Delaware Bay MLLW DBOFS.

But it appears to be any of the stations in Delaware bay. I need to do more testing on this to see which other areas are seeing this.

![image](https://user-images.githubusercontent.com/82955395/145310128-c003561d-8378-44f9-b7b3-51a159369a98.png)

**Comment by mpiannucci** [comment]
@jamesdoyle21 this should be corrected on the station harvesting, NOT the modelling. It looks like the COOPS water level data is being harvested at the sea level datum when it should be done at the MLLW datum instead

**Comment by jamesdoyle21** [comment]
@cpaternostro want to make sure you see this thread too.

**Comment by cpaternostro** [comment]
I can run some tests to assure that the modeling - observation = MLLW -
MSL
If that is true, then it will be an easy change to harvest the MLLW data at
each station.
However, in the future we may need to consider being flexible and allowing
MSL or even MHHW data calls for the observations.
I'll run some analyses today.


--

Chris Paternostro

https://tidesandcurrents.noaa.gov/

(w) 240-533-0587

**Comment by cpaternostro** [comment]
Delaware Bay:
Datums for 8555889, Brandywine Shoal Light DE  MSL = MLLW + *.79 m*
 Average difference between obs - model =  *0.842272495 m Loving the
permalink
<http://20.85.242.58/?permalink=N4IgtghgDgQjD2APEAuUB9Azgd1aANgHYDmqAtAOwCsAdAJwAcADACwBMAjHSy8wMxUOAGhD4IAF1R8GNAGxUWdCkwotqspnSoBfEekIBTPKJLlVNTQxZUt1Firp0RYySj50afWRwpsGHWQY2JjY2PhZtXXBoAGVxAE98IzQQAEsAE1QQCAAnAGMAcVTMABV4KHhiHOgAC1S8kBFCCDBkkDKKqtr6xpBxGoBXMAAjZtT8LJrxcShMFAB6ecwDHIA3FZpcvOJi+EJ8VMMaPPgwea2dzHmcg0xxJZXV+tv5gHV4HPx09A74dABZaDzQFQGKPFbzcTjAzzJiw2G9O6JZKgdY5TCpPaoBgiTDwAb5W7GcTlSrVKB1BopBJQNrVO4rXpQpKYVAAbRAUxmc0WyzWGwuu32hwMx1O53yl2ut3ufKeeRe70+31+AKBILB-JykOh82AAC9tHr4kbgIhtCAALoiZkGGKpfXJNhUWQiCTiHKpYYDKFYlAgECRZwQeIrVkoNmgDJZEmdcmUpnxWlZeniRm4-GEmOkroUnoiMCHfXwU6oJgFiCIYullChbSWoMgZZJPJp9IAYQkEHwlQAkmmwOGOYR4Jh0OlhvAAGZjgxJVYSTGEdBgfD4XAiE7lMcnNcGVtLq0ibCDsHTQ7EcOgEdjifT2fzxd7Fdr3ApaP+1MQ9IGKcQAb4JIBaHGWFbIG4Ig-n+AHiP8IEoOWIBQf+gGAuBbAiNUJAGCU9QANZDuWwgYXw1ogLuHwAEotFAWTDPgAxGCIBjNPRBjtvAPY5NRYC0SgHqMTaEDjICxCEKk4gDD+qB-vgywVmJElSQYAAyEDDHOMndvJIAsepSQlMJ+CieJknSSgsk6XpbHUdhqACQYzGsUkcSeukF5aXJjm6c5BgmUpP5qRpEwWdp3nWQZ1RTlO9QqakxBTPZOSCT5+nsXsJIEuGlneWIoY5AA8lAEB5BJ8SoBwTCIXcbnJIhWHECi4DwYhkDoVEyEwQAqjW4C9AMvVgIGUR5ASNyELB0C4a0DJ8SAwScGQHBsGQmglAECFMJtFhVQAWr0kBQNNMoGFAtmNey80hBwS0rSoJRMFQm3bVVTD7SIC03ctS0cA9T1VS9e1HiAAymTE8QMkN-qtB6PTaEAA>*
Datums for 8546252, Bridesburg PA     MSL = MLLW +  *3.59 ft*   Average
difference between obs - model = *3.189800629 ft  Link
<http://20.85.242.58/?permalink=N4IgtghgDgQjD2APEAuUB9Azgd1aANgHYDmqAtAOwCsAdACwBsdADBQJx0AcnjnVdAGhD4IAF1QBmNjQpdOE6g3bNGARgYBfIekIBTPMJLlZNKhQBM5ip1VVWbNg05CR4lCxr2655lVU+KCn8NLXBoAGVRAE98fTQQAEsAE1QQCAAnAGMAcQTMABV4KHhidOgACwTMkCFCCDA4kELi0oqqmpBRcoBXMAAjOoT8VPLRUShMFAB6KcxddIA3eZoMzOI8+EJ8BL0aTPgwKdX1zCn03UxRWfmFqoupgHV4dPwk9Gb4dABZaCmfqHCN3mU1EQ10U2YEIhHUuMTioCW6UwCU2qGcIEw8G6WQuBlERRKZSglWq8WiUEaZUu8w6oNimFQAG0QKNxpMZnNFstjhstjtdHsDkcsiczhcrpzbpl7k8Xm8Pt9fv9AVz0iCwVNgAAvDSaqK64CIDQgAC6QjpunCCS1cXMVAYQjEonSCT63VBqJQIBAIRcECi8wZKEZoGSqXxLSJJNpUQpqSpohpQkx2Ol4YJrWJ7SEYB2WvgB1QzBzEEQ+cLKEsGhNvoxulimUTSQAwmIIPgSgBJRNgIPMwjwTDoJJ9eAAMyH9d0CzEKMI6DA+HwuCE+yKQ-2S90jbnpqE2F7gLGO2IQdAA6HI-Hk9iM4988Xy4MYa9CeBSV0Y4g3Xw4hzOyLEtkBQaQeDtcwhA-L8f1EL4AJQYsQCg79fx+YCIJAMoSF0fIqgAaz7YtVAECCJDNEBN2eAAleooFSPp8G6fQhF0OoGN0Zt4A7dIaLAOiUGdJjzQgIYfmIQgElEboP1QL98DmEtxMk6TdAAGQgPp61k9sFJAViNNifIRPwMSJKkmSUDk3T9PYmjsNQQTdBYtjYkiF0khPbT5KcvSXN0UzlI-dTNOGSydJ8mzDLKMcxyqVSEmIUYHPSITfIMjjNnxbEgysnyRADdIAHkoAgTJJKiVBVGYRDLncuJEKw4h4XAeDEMgYCGFMBh1E4UJkJggBVCtwA6bphrHP9Omi2LMjgwhAKmiAYqqNCi1rTJsXOQhYOgXCGmpfiQB8cxVDIfwyGYNh8nUBDmFuzxqoALQ6SAoD28VdCgOymqZI7mBOs7TuYThroYW77uq5hnqEY7TvOy7QfB6qHqhvcQG6MzwiiakwFSBI+PmBJ2x9IA>*

Chesapeake Bay:
Datums for 8638901, CBBT, Chesapeake Channel VA,  MSL = MLLW + *0.78
ft*  Average
difference between obs - model = *0.414920972 ft*
Datums for 8638610, Sewells Point VA,  MSL = MLLW + 1.36 ft  Average
difference between obs - model = *0.414920972 ft*

Anecdotally, there seems to be a problem with the shift from model to
observations.  However, I compared the time series of CO-OPS stations
through OM and via T&C website.  I am validating that, for the few stations
checked, WL obs and predictions data through OM matches exactly (even with
higher precision) data on T&C with the parameters Timezone=LST and
Datum=MLLW.  So the harvesting of the obs and preds data by the backend of
OM seems to be correctly using MLLW.

With the simple solution put aside, this now raises bigger questions.
 I'll have to begin evaluating model data.
It'll take me some more time to investigate this.  But this is good,
anyway, because I should develop a robust set of semi-automated tests to
check that the OM frontend is correctly disseminating CO-OPS station, obs,
preds and model data for ALL stations.

--

Chris Paternostro

https://tidesandcurrents.noaa.gov/

(w) 240-533-0587

**Comment by jamesdoyle21** [comment]
@tgiguere @patrick-tripp

**Comment by cpaternostro** [comment]
The vertical grid offsets that @Kelly Knee ***@***.***> was
talking about yesterday can be found here at this FTP site Kelly also
mentioned.
ftp://tidepool.nos.noaa.gov/pub/outgoing/OFS_Grid_Datum/

--

Chris Paternostro

https://tidesandcurrents.noaa.gov/

(w) 240-533-0587

**Comment by jamesdoyle21** [comment]
@cheryldmorse

**Comment by jamesdoyle21** [comment]
The files live here: http://data.oceansmap.com/thredds/catalog/coops/catalog.html I’m not seeing any metadata about the reference datum in the files but it is MLLW. - from Cheryl

**Comment by jamesdoyle21** [comment]
@jonmjoyce

**Comment by mpiannucci** [comment]
@cpaternostro We took a look at those offset files and it looks like those are for the original grids and not for the new RegularGrid configs that we have been using for visualizing the ROMS data. Do you think it would be possible to get these offset nc files translated to the same regular grids so we can be sure they are being applied correctly before serving the data? Thanks!

**Comment by cpaternostro** [comment]
I'll see if the modeling team can create such a file.
Thanks for finding this problem.

--

Chris Paternostro

https://tidesandcurrents.noaa.gov/

(w) 240-533-0587

**Comment by cpaternostro** [comment]
I just talked to the modeling team who told me that the regulargrid netCDF file contains a variable called, "zetatomllw" which is water level references to MLLW.

        float zetatomllw(ocean_time, ny, nx) ;
                zetatomllw:long_name = "free-surface referenced to mean lower low water" ;
                zetatomllw:units = "meters" ;
                zetatomllw:time = "ocean_time" ;
                zetatomllw:grid = "grid" ;
                zetatomllw:location = "face" ;
                zetatomllw:coordinates = "Longitude Latitude ocean_time" ;
                zetatomllw:field = "free-surface, scalar, series" ;
                zetatomllw:_FillValue = -99999.f ;
Try to use use this variable to correct the WL to MLLW

**Comment by jonmjoyce** [comment]
Thanks for identifying that, @cpaternostro . So in order to represent the actual MLLW values I'm thinking I would create a new variable (named mllw) that would be a transformation from zeta. What is the correct conversion formula using zeta and zetatomllw?

Also what models does this need to be applied to?

**Comment by mpiannucci** [comment]
This needs to be applied to every regulargrid OFS model. 

Hm, wait @cpaternostro is that variable the offset between zeta and MLLW or is it the zeta in the MLLW datum (IE doesn't need to be transformed?)

**Comment by cpaternostro** [comment]
I am creating a meeting for tomorrow with the modeler who knows this data.  Do y'all want to join the meeting?  If so what time is good for you?

**Comment by mpiannucci** [comment]
I can make time anytime except between 1 and 3

**Comment by jamesdoyle21** [comment]
Same with me. Anything besides 1-3

**Comment by mpiannucci** [comment]
@jonmjoyce No transformation needed, the variable shows the value of zeta referenced to MLLW, so its already transformed here

https://opendap.co-ops.nos.noaa.gov/thredds/godiva2/godiva2.html?server=https://opendap.co-ops.nos.noaa.gov/thredds/wms/NOAA/CBOFS/MODELS/2022/01/19/nos.cbofs.regulargrid.n006.20220119.t12z.nc

**Comment by mpiannucci** [comment]
So in other words.... no action is needed for this from you anymore. Thank you!

**Comment by mpiannucci** [comment]
New task is: Update ott catalog to point to zetatomllw for waterlevel layers

**Comment by patrick-tripp** [comment]
Same here. Anytime except 1-3.


Patrick Tripp
Principal Software Engineer
RPS | North America
T  +1 401 661-8642
E  ***@***.******@***.***>

From: Chris Paternostro ***@***.***>
Date: Tuesday, January 18, 2022 at 4:35 PM
To: asascience/ott-coops ***@***.***>
Cc: Patrick Tripp ***@***.***>, Mention ***@***.***>
Subject: Re: [asascience/ott-coops] Fix the 2.94 ft Offset when Validating Waterline Data in Delaware Bay (Issue #223)

I am creating a meeting for tomorrow with the modeler who knows this data. Do y'all want to join the meeting? If so what time is good for you?

—
Reply to this email directly, view it on GitHub<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fasascience%2Fott-coops%2Fissues%2F223%23issuecomment-1015854469&data=04%7C01%7Cpatrick.tripp%40rpsgroup.com%7Ca5a3eb80ceb140b571e608d9daca753c%7C49833998a8f1424bbf845d50f102d530%7C0%7C0%7C637781385349557518%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=hiQ39zZDcpyH86c3me9yggz4vpB3ZTUX1s3EN5zq1fo%3D&reserved=0>, or unsubscribe<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAKRZYDBOAM6CDDAN2VHN2YLUWXMKJANCNFSM5JU2GDQA&data=04%7C01%7Cpatrick.tripp%40rpsgroup.com%7Ca5a3eb80ceb140b571e608d9daca753c%7C49833998a8f1424bbf845d50f102d530%7C0%7C0%7C637781385349557518%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=fOx5NYbUpvs9NB9qENmOjFzG8a4dFsUmLSCz%2Bf7GDAc%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cpatrick.tripp%40rpsgroup.com%7Ca5a3eb80ceb140b571e608d9daca753c%7C49833998a8f1424bbf845d50f102d530%7C0%7C0%7C637781385349567474%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=gir6Ui2pjxBhhEAQjs4bqIos4kHhYPY%2FhLDQ7V%2Bh7XI%3D&reserved=0> or Android<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cpatrick.tripp%40rpsgroup.com%7Ca5a3eb80ceb140b571e608d9daca753c%7C49833998a8f1424bbf845d50f102d530%7C0%7C0%7C637781385349567474%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=oeUqhhZSjXn4%2FfVszV5KclExJI%2FlqEjhvbSaOvumEE4%3D&reserved=0>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

This e-mail message and any attached file is the property of the sender and is sent in confidence to the addressee only.

Internet communications are not secure and RPS is not responsible for their abuse by third parties, any alteration or corruption in transmission or for any loss or damage caused by a virus or by any other means.

RPS Group Plc, company number: 208 7786 (England). Registered office: 20 Western Avenue Milton Park Abingdon Oxfordshire OX14 4SH.

RPS Group Plc web link: http://www.rpsgroup.com<http://www.rpsgroup.com/>
