### ISSUE TITLE
Wave Direction Layers Color Palette Only Showing East

### ISSUE THREAD

**Issue by jamesdoyle21** [asascience/ott-coops#264]
I understand there is no magnitude with this data layer, but I would expect the color palette to have the other directions listed, right? It would at least fill out that color palette image as it looks a bit odd with just "E"

![image](https://user-images.githubusercontent.com/82955395/150151817-3d2a949d-a921-4bf1-83b0-e836eecccf04.png)

**Comment by mpiannucci** [comment]
No that's not how it works, this is what pyxms does for single direction layers

**Comment by jamesdoyle21** [comment]
Alright, if we haven't heard anything about this from users, no need to add to the scope. I think it looks a bit weird, but if that is always how it has been, lets leave this one

**Comment by mpiannucci** [comment]
> Alright, if we haven't heard anything about this from users, no need to add to the scope. I think it looks a bit weird, but if that is always how it has been, lets leave this one

This is directly the spec from FMIS and it comes from pyxms, so really should not change this unless we really need to. 

There also isnt much info to show, its kinda pointless in my opinion to have all the directions there for no reason. Remember for vector layers it shows multiple arrows because the color changes with the speed, but for scalar direction layers all it is showing is the direction.
