### ISSUE TITLE
Create Different Marker Shapes for Grouping of Stations 

### ISSUE THREAD

**Issue by jamesdoyle21** [asascience/ott-coops#266]
Yesterday, Chris brought up the idea of adding another layer of grouping to the data station layers. Some of these layers, like CO-OPS Stations, for example, have hundreds of pins. Can we further group these stations by the type of data they collect (ie any station with current data is square).

@cpaternostro we will need some guidance into how many groups and what the criteria is for them

**Comment by kvmartin001** [comment]
@jamesdoyle21 when you say grouping, do you mean using just one pin to represent a cluster of nearby pins like this?
[https://docs.mapbox.com/mapbox-gl-js/example/cluster/](https://docs.mapbox.com/mapbox-gl-js/example/cluster/)

It's also possible to have different markers based on any criteria in the data.

**Comment by mpiannucci** [comment]
No, he means make the marker a diff shape for different sensor types

**Comment by cpaternostro** [comment]
I'd like to mimic the view of NOAA's Tides and Currents station selection
webpage <https://tidesandcurrents.noaa.gov/map/index.html?region=Florida>.
This page does have station clustering when zoomed out.  I like that, and
if you zoom into a cluster you will see different colored pins for
different types of stations (Water Level and Met, Water
Levels, Meteorological, Air Gap, Currents).  I like how OceansMap shows the
CO-OPS data with a blue pin, but it would be nice to differentiate these
different types (sensors) with various shapes of blue pins.

--

Chris Paternostro

https://tidesandcurrents.noaa.gov/

(w) 240-533-0587

**Comment by jamesdoyle21** [comment]
@cpaternostro do you like these 5 groups, specifically? Or do we want to modify this list?

![image](https://user-images.githubusercontent.com/82955395/150192804-9f4e692c-f2e3-42a6-8006-01e6b9ad8d52.png)

**Comment by jamesdoyle21** [comment]
@kvmartin001 grouping by sensor(s) at each station. But you do bring up a good point that grouping stations when the user zooms out is also a nice feature. We would have to think about how that would work with pins with different shapes, shade, and color.

**Comment by mpiannucci** [comment]
> @kvmartin001 grouping by sensor(s) at each station. But you do bring up a good point that grouping stations when the user zooms out is also a nice feature. We would have to think about how that would work with pins with different shapes, shade, and color.

Some history, We do this is in OM1 currently with a custom clustering algorithm, originally we were planning to implement the algorithm but never got around to it because its a tough problem to think of, and to handle

**Comment by kvmartin001** [comment]
> We do this is in OM1 currently with a custom clustering algorithm

I can see why. But making different marker shapes is straightforward. I can use premade SVGs or make them in Inkscape, then grab the SVG code and put it in MapUtils. We can modify any part of the SVG with data-driven properties, like the fill / stroke color of different parts of the marker.

**Comment by cpaternostro** [comment]
Yes,
This list is best for creating the shapes of the blue CO-OPS stations.

--

Chris Paternostro

https://tidesandcurrents.noaa.gov/

(w) 240-533-0587

**Comment by jamesdoyle21** [comment]
@cpaternostro this issue is deployed, take a look and see how you like it. Also, did we want to do something similar for the other data station layers, or was this specific to CO-OPS?

**Comment by kvmartin001** [comment]
Hi @cpaternostro, I had some follow up questions about this. 
We are currently binning the stations by looking at the data `tags` list. The coops_collection has about 70 unique combinations of tags, and I binned those unique combos into four categories by hand.

Two questions here -

•	I’m noticing differences in station locations and data between NOAA's site and OceansMap 3. In New York Harbor for example, NOAA’s site has more stations. We also have no air gap stations as far as I can tell. Should our map match NOAA's exactly?

![image](https://user-images.githubusercontent.com/56608780/153062870-0a0d1592-170c-4b36-8944-9bdf624511d1.png)

![image](https://user-images.githubusercontent.com/56608780/153062908-2704d3b2-e120-42bb-ad37-4b2b024ece5b.png)

 
•	How is the NOAA site binning the stations? I am not sure if going by the tags is the best method. I had to make our categories different than NOAA's list because there was no `air gap` tag and there were many stations that had water quality + met data, but not water level.


NOAA CO-OPS site categories:
- Water Level and Met
- Water Levels
- Meteorological
- Air Gap
- Subordinate
- Currents

OceansMap 3 categories:
- Water Levels (only water level measurements)
- Currents (only water current measurements)
- MetOcean (any combination of air- and water-based measurements)
- Meteorology (any combination of air-based measurements)

**Comment by cpaternostro** [comment]
Hi Kevin,
I'll have to look into what Subordinate measurements are, otherwise, I'd
like to match the data display of CO-OPS Tides and Currents website as
closely as possible.  Air Gap is definitely needed by the mariners to
safely get under the bridges.
Thanks for asking,
Chris

--

Chris Paternostro

https://tidesandcurrents.noaa.gov/
