### ISSUE TITLE
NWPS Direction Layers have Color Palette Options

### ISSUE THREAD

**Issue by jamesdoyle21** [asascience/ott-coops#330]
This should not be an option, for any vector layer, correct? Or are the arrows themselves supposed to have the color scale?

![image](https://user-images.githubusercontent.com/82955395/152832242-f9eb26fd-2e75-4c9f-927f-28f5e079d732.png)

**Comment by jamesdoyle21** [comment]
OM1 does not have the color palette option

**Comment by jamesdoyle21** [comment]
Wind does this too

![image](https://user-images.githubusercontent.com/82955395/152838806-4dac7c53-3689-48e2-a107-830c0f699162.png)

**Comment by kvmartin001** [comment]
@nguyandy does EDS support color palettes for this data? If not, I can just add a check for the layer type to disable the palette dropdown here.

**Comment by nguyandy** [comment]
I don't think it does, I'm not seeing palette options for any of the winds layer in OM1 either.

**Comment by kvmartin001** [comment]
@jamesdoyle21 This was fixed in this PR: https://github.com/asascience/oceansmap-3/pull/208

Six of the direction layers in the Maracoos catalog are coming from EDS and they are fixed by my PR (sort of by accident)
EDS only returns one style option for direction layers, and we decided to hide the dropdown if that is the case.

- SECOORA CNAPS Wave Direction
- Chesapeake (NWPS Wave Direction)
- Boston (NWPS Wave Direction)
- New York/Upton (NWPS Wave Direction)
- Mount Holly/Philadelphia (NWPS Wave Direction)
- Global (WW3 Direction)

The other two are coming from pyXMS and should be able to change arrow color. I'm not seeing tiles for these right now, but their WMS Settings are correct

- Atlantic 10m (WW3 Wave Direction)
- NECOFS Wave Direction

**Comment by jamesdoyle21** [comment]
Niiiice
