### ISSUE TITLE
Units not Updating for Water Temperature Layers and Not Showing in Settings Drawer

### ISSUE THREAD

**Issue by jamesdoyle21** [asascience/ott-coops#337]
All layers except Doppio Bottom do not update to F when switching to imperial

![image](https://user-images.githubusercontent.com/82955395/152853361-50955cd9-4a1b-48b9-98d8-5dcc14675afa.png)

**Comment by jamesdoyle21** [comment]
This is similar to #336

**Comment by nguyandy** [comment]
Related to this issue.
https://github.com/asascience/ott-coops/issues/267

Doppio is a pxyms layer, so that's why its working.
With EDS layers, OM3 doesn't know the unit type until we make a GFI request - and we need the unit type in order to do conversions. 

We could add a hardcoded unit mapping for some eds layers for now, but it's not a permanent solution.


Same issue as https://github.com/asascience/ott-coops/issues/336

**Comment by jamesdoyle21** [comment]
Ok, thanks Andy. We don't want to spend the time on this until a more permanent solution is available. I will take these off the sprint and combine with #336

**Comment by jamesdoyle21** [comment]
![image](https://user-images.githubusercontent.com/82955395/152855989-fe1a80c0-2e7a-4aad-ad8a-1b23780d38c1.png)

**Comment by jamesdoyle21** [comment]
Same with salinity, currents and waterlevel
