### ISSUE TITLE
Maracoos Climatology Layers return blank tiles

### ISSUE THREAD

**Issue by ndellicarpini** [asascience/ott-coops#338]

**Comment by jamesdoyle21** [comment]
There are several other layers in the MARACOOS catalog that gave no response and may be the same issue as this. Take a look at the spreadsheet in the Teams chat and maybe this fix can cover more than just the climatology layers.

If you do find that this issue is the same as other layers, if you could make a quick note in the spreadsheet, that way we are looking big picture

**Comment by ndellicarpini** [comment]
Sounds good. What I will note is this is a different issue than "No Response", as these layers successfully fetch & load (aka loading spinner responds), but every tile that comes back is blank. A layer returning all blank tiles is a huge flag for it being a pyxms issue.
