### ISSUE TITLE
Move the Legend under each variable in the Data Layers pullout menu

### ISSUE THREAD

**Issue by cpaternostro** [asascience/ott-coops#375]
Instead of having a separate Legend pull out drawer on the right side of the map.  I propose that we just show each variable's legend/scale, under the checked (turned on) data layers.  This way, users can have the scale available to them as soon as the variable is checked on plus, clicking no the Active Layers tab will provide a concise listing of legend values.  We could even rename it Legend.
I have attached a mock-up for waves and CO-OPS obs.

![image](https://user-images.githubusercontent.com/62911145/154767744-d1e0712e-531f-4869-808d-b88343842980.png)

**Comment by mpiannucci** [comment]
I understand why this is desirable , we flirted with it a little but (code) design wise it would be a pretty big change to the way the app is structured. Since layers don't have to come from the data layers tool, they can come from any tool (like the traffic light tool. So in order for this to be effective, we'd have to duplicate a lot of logic and track everything on a per tool basis instead of having one Legend API that any kind of layers can hook into and show their legends consistently. 

That's not to say we can't build something specific that does work like this if it is a deal breaker, but hoping to start dialog around why it is how it is now.
