### ISSUE TITLE
Deselect the Zoom to Box Selection Tool by Clicking on Button 

### ISSUE THREAD

**Issue by jamesdoyle21** [asascience/ott-coops#410]
I know the esc key deselects the zoom to box tool, but Sheri didn't find that clear and it's the second time it has come up, so we should also let the user deselect by re-clicking it

**Comment by ndellicarpini** [comment]
We really need a notification or something similar for tools that use the escape key, as I believe all of the gis & measurement tools work the same way. I think I have an idea on how to get this tool to turn off by clicking the button again, but let me preface by saying that both matt and I tried to do this unsuccessfully in the past.

**Comment by jamesdoyle21** [comment]
If there is a good way to notify the user about the esc key, I am all for it. Then we don't need to battle with a second click

**Comment by mpiannucci** [comment]
The second click does make sense, but need a notication of some kind to notify about the escape key, like teams has when you are sharing your screen or whaterver

**Comment by ndellicarpini** [comment]
Here's a concept of what I think we should do. I'm torn about how it appears over everything because it looks strange being on top of the drawers & map tools, but I think it's important that it appears over the `Edit Custom Layer` drawer. What do you guys think?

https://user-images.githubusercontent.com/22432482/161771233-85b5414a-f949-4a72-adfb-6aac466d6c2c.mp4
