### ISSUE TITLE
Measure Tool Weirdness

### ISSUE THREAD

**Issue by jamesdoyle21** [asascience/ott-coops#419]
Few things I noticed while testing the measure tool:
- It took me a long time to figure out how to create a line with multiple vertices (and not sure it was the way we intended)
- Opening the GIS Tool allowed me to create a second line to measure which did allow for multiple vertices
- Can the Esc key exit the tool like it does for the bounding box tool?
- When zoomed out, the tooltip does not land on the drawn line
- Double clicking shows nothing, then user needs to deselect and reselect tool to measure again
- Capitalize the D in "Measure distance" tooltip

**Comment by jamesdoyle21** [comment]
https://user-images.githubusercontent.com/82955395/161612241-b33958ea-642e-495e-95a3-d4075715e269.mp4

**Comment by jamesdoyle21** [comment]
![image](https://user-images.githubusercontent.com/82955395/161612293-b7b95308-e192-458d-b837-59a795de2f44.png)

**Comment by jamesdoyle21** [comment]
Steps to reproduce the bug allowing for a second (and third) line to be drawn:
- Draw line with measure tool
- Open a drawer from any tool
- Draw a second line (which allows for multiple vertices)

![image](https://user-images.githubusercontent.com/82955395/161613776-0e0b36e8-6a21-4dea-b978-8ee49493e945.png)

**Comment by kvmartin001** [comment]
Yeah when Measure is activated, I have a limiter on the drawing functionality that says "only allow one line with two vertices". It looks like the limiter is breaking sometimes.

The drawing session is getting re-initialized when you open and close another tool, and when that happens, the limiter doesn't get applied so you get the normal line drawing tool.

The popup is supposed to appear at the midpoint of the most recently active feature, so that would be the last one you drew or the last one you selected. (the limiter is supposed to make multiple features impossible)

No idea why the tooltip coordinates are wrong though.

**Comment by kvmartin001** [comment]
@jamesdoyle21 the tooltip position is actually "correct" because it's following the geodesic line between the points.

But that's still problematic, so I'm looking for a way around this.

Our map (Mercator)
![image](https://user-images.githubusercontent.com/56608780/163030974-c197a83b-b7ff-4ddd-8302-59db080b0afa.png)

Google Earth 3D
![image](https://user-images.githubusercontent.com/56608780/163031115-16f1d360-b5f9-40fb-b2fd-af027103561d.png)

**Comment by jamesdoyle21** [comment]
Are we intentionally not allowing for a line with multiple vertices? Is it problematic? I can see it being useful when a user is mapping out a route

**Comment by mpiannucci** [comment]
For now i said to simplify it to start because there was a lot of weirdness with multiple vertices

**Comment by jamesdoyle21** [comment]
Ok, got it. I'll close it and we can think about adding functionality in the future as needed
