### ISSUE TITLE
Custom Layer Tool Draws Underneath Loading Layers

### ISSUE THREAD

**Issue by jamesdoyle21** [asascience/ott-coops#422]
The easiest way to solve this is probably to only allow the user to start drawing after all layers have loaded in.

![image](https://user-images.githubusercontent.com/82955395/161628370-368bd82a-7bc0-42a2-82a0-dece6dff48d5.png)

**Comment by kvmartin001** [comment]
It might actually be easier to add the editing layer(s) to the sorting config.

@ndellicarpini if I have a bunch of map sources that all start with a certain string, can we configure them to always be on top?

The drawing plugin adds like 30 sources to the map, one for each type of geometry it needs x2 for blue and orange

**Comment by jamesdoyle21** [comment]
This is actually happening to me after layers are loaded in now. But I'm not positive what the steps are to reproduce

![image](https://user-images.githubusercontent.com/82955395/161629492-fd21d4c2-c0fa-40f4-b233-e9e70e51a43c.png)

**Comment by ndellicarpini** [comment]
I don't think we can use the layer sorting for the active editing layer because they aren't added to the map like our other layers, they are kind of sneakily added to the map layers. I think you're going to have to move the layers yourself, ignoring any layer sorting. 

When the layers get added, find all of those layers with that string and use this: https://docs.mapbox.com/mapbox-gl-js/api/map/#map#movelayer
