### ISSUE TITLE
NOAA New York MLLW (NYOFS) is not turning on, and NOAA New York Currents (NYOFS) is not in the catalog.

### ISSUE THREAD

**Issue by jamesdoyle21** [asascience/ott-coops#431]
OceansMap Bug tracker line 26

NOAA New York MLLW (NYOFS) will not even allow the user to check the box

**Comment by ndellicarpini** [comment]
@nguyandy is this a catalog issue? I don't even see NOAA New York when I load the ott catalog on master, but it's clearly on https://dev.oceansmap.com/ott-coops/.

**Comment by nguyandy** [comment]
Some of the layers are erroring out on pyxms, so they're not added to the `maracoos-om3` s3 catalog when data-catalog builds it out.

https://dev.oceansmap.com/ott-coops/ has a service running beside it that reindexes the new catalog without removing layers that don't currently exist in the s3 catalog - which is why you're seeing it there, but not locally.

@patrick-tripp can you take a look at the datasets that are erroring out? Seeing this error for most of the problematic datasets.
```
Caused by:
java.lang.IllegalArgumentException: Coordinate values must increase or decrease monotonically
uk.ac.rdg.resc.edal.grid.AbstractIrregularAxis.checkAscending(AbstractIrregularAxis.java:114)
uk.ac.rdg.resc.edal.grid.AbstractIrregularAxis.init(AbstractIrregularAxis.java:103)
uk.ac.rdg.resc.edal.grid.AbstractIrregularAxis.<init>(AbstractIrregularAxis.java:64)
uk.ac.rdg.resc.edal.grid.TimeAxisImpl.<init>(TimeAxisImpl.java:52)
uk.ac.rdg.resc.edal.util.cdm.CdmUtils.createTimeAxis(CdmUtils.java:313)
```

**Comment by mpiannucci** [comment]
@nguyandy @patrick-tripp is on it, he got it fixed for SFBOFS last week, but needs to make sure the fix works for all layers

**Comment by patrick-tripp** [comment]
NYOFS ncwms2 is working correctly now.

**Comment by mpiannucci** [comment]
Working correctly but data catalog needs an update to be able to catch date errors without throwing all the valid dates out the window
