### ISSUE TITLE
Current direction, water velocity, and water temperature does not populate any comparison model data in validation tool

### ISSUE THREAD

**Issue by jamesdoyle21** [asascience/ott-coops#443]
OceansMap bug tracker line 64

These parameters do not allow the user to select a comparison model

![image](https://user-images.githubusercontent.com/82955395/163243610-d53e72b6-8987-4bfe-ad4c-bfe149ed218d.png)

**Comment by ndellicarpini** [comment]
Can you give an example of at least 1 comparison that should exist for each of the parameters mentioned in the issue?

**Comment by mpiannucci** [comment]
Currents are tough because they are vector groups. You will need to specifically request -mag or -dir to get the comparison. I dont think i brought over the code for doing directional comparisons,  so stick with just doing the speed for now and we can open another ticket for the directional comparisons 

This one has current data: 

Observation: 
cb0102

Comparison:
CBOFS

**Comment by jamesdoyle21** [comment]
For example, I should be able to validate water temperature for station 44008 vs Global HYCOM Navy. I can compare the two in the obs drawer, but I don't have the option to select the parameter or comparison in the validation tool

![image](https://user-images.githubusercontent.com/82955395/167694148-53546a09-ceaa-4001-8ec4-73ebed3859a8.png)
