### ISSUE TITLE
Add the following NOS models to the data catalog:  

### ISSUE THREAD

**Issue by cpaternostro** [asascience/ott-coops#468]
1. SJROFS
2. NGOFS2
3. LEOFS
4. LOOFS
5. LSOFS
6. SFBOFS

**Comment by jamesdoyle21** [comment]
@patrick-tripp

**Comment by mpiannucci** [comment]
To Flesh this out.... they currently are mis configured in thredds and therefore the catalog doesnt have their data and then oceansmap and its data catalog will not work because they do not show in ncwms. 

Once their thredds config is fixed they should be able to be added back into oceansmap

**Comment by jamesdoyle21** [comment]
ngofs2 appears to be working fine. The others worked fine with TDS 5.0 beta version we were using. There is an issue with the time axis on at least some of those that TDS or ncWMS2 is complaining about.

-from Patrick

**Comment by mpiannucci** [comment]
I added NGOFS2 to OTT catalog today so hopefully it will be up tomorrow

**Comment by mpiannucci** [comment]
Tracking missing NOS models:

- [ ] SJROFS
- [x] NGOFS2
- [x] NYOFS
- [x] LEOFS
- [x] LOOFS
- [x] LSOFS
- [x] SFBOFS

**Comment by mpiannucci** [comment]
For SFBOFS... There error shows as such: 

![Screen Shot 2022-05-24 at 11 22 36 AM](https://user-images.githubusercontent.com/1832671/170072794-e6e51792-46b1-4ec5-9adb-c21c1d437bf4.png)

Which is saying that the time axis does not increase monotonically. But if we query the time variable from THREDDS it does indeed look correct: 

https://eds.ioos.us/thredds/dodsC/ioos/ofs/sfbofs/forecast/regulargrid/SFBOFS_Forecast_Regulargrid_best.ncd.ascii?time%5B0:1:1366%5D

Ok, So then looking at the time_run variable and these are not monotomic: 

https://eds.ioos.us/thredds/dodsC/ioos/ofs/sfbofs/forecast/regulargrid/SFBOFS_Forecast_Regulargrid_best.ncd.ascii?time_run%5B0:1:1366%5D

![Screen Shot 2022-05-24 at 11 26 51 AM](https://user-images.githubusercontent.com/1832671/170073634-7f118c31-1b4a-42d3-8c2f-719dddda2190.png)

Which is expected because this is an FMRC. and the best timestep may vary by model run. OK so do the other RG files just work? Lets check CBOFS: 

https://eds.ioos.us/thredds/dodsC/ioos/ofs/sfbofs/forecast/regulargrid/SFBOFS_Forecast_Regulargrid_best.ncd.ascii?time_run%5B0:1:1366%5D

That looks monotomic: 

![Screen Shot 2022-05-24 at 11 28 22 AM](https://user-images.githubusercontent.com/1832671/170074061-d4c3a7c9-49ed-4e43-81b0-81c3fcb3a53e.png)

So either some of the timesteps for SFBOFS are missing data but NCWMS cant handle that (even though it definitely should), or there is a configuration gap between how CBOFS is configured in thredds and how sfbofs is. CC @patrick-tripp

**Comment by mpiannucci** [comment]
I noticed that the CBOFS thredds config declares `<dimension name="time" orgName="ocean_time"/>` but SFBOFS doesnt. But then I checked and DBOFS doesnt declare it either and that works fine so im not sure that matters at all

**Comment by mpiannucci** [comment]
Success. @patrick-tripp was able to nail down the fix tonight and the other models will be filtering in soon as the fix is applied and data-catalog for OceansMap is updated to match.

**Comment by patrick-tripp** [comment]
The fix is only working intermittently. I will continue to investigate.

**Comment by patrick-tripp** [comment]
FYI: time_run and time_offset are axis created by THREDDS when computing the Best timeseries.

**Comment by mpiannucci** [comment]
@cpaternostro Is it possible to get NYOFS to be published with regulargrid data like CBOFS and DBOFS etc (including the zetatomllw field)? If not its no big deal, but it wont be consistent with the other models we have

**Comment by mpiannucci** [comment]
Update data catalog for a bunch of these, hoping to see more rendering correctly tomorow

**Comment by mpiannucci** [comment]
Ok! So all of these now show up in the UI, but the Fields ones have messed up time ranges and so they do not render because data-catalog is confused by them: 

```
data-catalog-dev    | 2022-06-16 14:51:11,902 - 1 - data_catalog - models:161 - ERROR - Failed to load WMS Layer - NYOFS/u:v-group
data-catalog-dev    | Traceback (most recent call last):
data-catalog-dev    |   File "/usr/share/data-catalog/data_catalog/generic/models.py", line 144, in from_wms
data-catalog-dev    |     start_time, end_time, timestamps = self.get_times(wms_service, layer)
data-catalog-dev    |   File "/usr/share/data-catalog/data_catalog/generic/ncwms2.py", line 249, in get_times
data-catalog-dev    |     date = dateparse(d)
data-catalog-dev    |   File "/usr/local/lib/python3.6/site-packages/dateutil/parser/_parser.py", line 1358, in parse
data-catalog-dev    |     return DEFAULTPARSER.parse(timestr, **kwargs)
data-catalog-dev    |   File "/usr/local/lib/python3.6/site-packages/dateutil/parser/_parser.py", line 654, in parse
data-catalog-dev    |     ret = self._build_naive(res, default)
data-catalog-dev    |   File "/usr/local/lib/python3.6/site-packages/dateutil/parser/_parser.py", line 1229, in _build_naive
data-catalog-dev    |     naive = default.replace(**repl)
data-catalog-dev    | ValueError: year 10014 is out of range
```

**Comment by patrick-tripp** [comment]
NYOFS has already been fixed and shows up okay in Godiva. LSOFS and LOOFS are fixed now and should start to appear normal soon. The problem was this line in the tds collection config.

attribute name="units" value="days since 9999-12-31T23:59:59.99"

**Comment by mpiannucci** [comment]
@patrick-tripp yeah they show up fine, but something is different about their metadata that data catalog is reading. It's a problem on my end I think, I'll let you know when I figure out more. 

Thanks for the hard work

**Comment by patrick-tripp** [comment]
@mpiannucci, I might be able to use ncml to modify the funky metadata.

**Comment by mpiannucci** [comment]
The only one left now is SJROFS

**Comment by mpiannucci** [comment]
The others will be working in OM beta after data catalog and oceansmap deployment today

**Comment by mpiannucci** [comment]
SJROFS: 



![Image](https://user-images.githubusercontent.com/1832671/174348833-26a5c677-f8b7-41b1-9f94-d4def199fe68.png)

**Comment by jamesdoyle21** [comment]
I don't see water level for LOOFS or LSOFS. Do we expect these layers to be avaiable?

**Comment by mpiannucci** [comment]
LOOFS and LSOFS dont have water level

**Comment by jamesdoyle21** [comment]
Gotchya. Closing this

**Comment by cpaternostro** [comment]
Because the NYOFS is a different grid, I hear that it doesn't do well to
interpolate it into a regulargrid.  This is probably the same reason why
you need it.
Would it be helpful for me to hold a meeting with you and the modeling team
so you can ask questions?

--

Chris Paternostro

https://tidesandcurrents.noaa.gov/
