### ISSUE TITLE
The NOAA Columbia River Estuary (CREOFS) Model Need to Show Currents, Temperature and Salinity as well

### ISSUE THREAD

**Issue by jamesdoyle21** [asascience/ott-coops#506]
Do we have these data layers available for OTT?

From Chris: "Chris Paternostro (email: [christopher.paternostro@noaa.gov](mailto:christopher.paternostro@noaa.gov)) left some feedback for OceansMap on 7/12/2022, 1:09:46 PM
The NOAA Columbia River Estuary (CREOFS) model need to show currents, temperature and salinity as well.
Right now it only has the water level part of the model available in the catalog 

Permalink:
https://dev.oceansmap.com/ott-coops/?permalink=N4IgtghgDgQjD2APEAuUB9Azgd1aANgHYDmqAtAIwBMALAHRUDMAbDUwBwAMAnO3zcwA0IfBAAuqGgFY67GoylSKi3lO7NmAX2HpCAUzwiS5alVnrGAdm6cpbRjXaXhoiSgF0rNGpZ6MqzJxUXDSa2uDQAMpiAJ74BmggAJYAJqggEABOAMYA4kmYACrwUPDEmdAAFknZIMKEEGAJIMWl5VU1dSBilQCuYABGDUn46ZViYlCYKAD0M5h6mQBui3RZ2cQF8IT4Sfp02fBgM+ubmDOZephi84tLNVczAOrwmfgp6K3w6ACy0DN-KCRO6LGZiEZ6GacKFQrrXOIJUArTKYJLbVDsYSYeC9HJXQxiEplCpQaq1RKxKDNCrXRZdcHxTCoADaIHGk2mcwWy1Wpy2Oz2egORxOOTOFyuN2592yjxebw+X1+-0BwJ5mTBEJmwAAXpptTF9cBEJoQABdYQMvSRJI6hJUKRCDITTJJAa9cHolAgACimFdggABLksmA9kHcj6YABhADyQYAcrGAILJwMJ3IAEWjQYghBSgfgPUWgcOhDErvdhJRIDCLggMUWTJQzNAqXShLaJLJ9JiVPSNLEdKxOLxHaJ7VJnWEYcIOvgR1QnBnEEQ88XKCoVE0ZrrIGwYEwwIme2IzdAhHgmHQ2Uu8AAZte9PEluI0YR0GB8PhcGg99lcUuctAUKJImlpKB0ioIIqDIThLEoKhCgoSwUE4Tg0M4Oh0M4AAtLpICgUDwKHKAACU82IBJWWgrc4IQihOEKTgaEwzDsPQ-DhFo2D4MoGhmNY9D2Jw-CLRAXpCCSMRIhiWkwHSJoK2nEAFnibIhxSSJZQaV14AAGQbJsWXE7FMk0wzG0yABJTNm1ZS9r1vPQHyfF8322T9v1wYRDgga5dn0JlxJScQIGjML8DKAAxEYh0yQxrldYxvUOfB+lrTQgA "

**Comment by jamesdoyle21** [comment]
@cpaternostro

**Comment by mpiannucci** [comment]
Ya its available now via thredds so ill try and update the catalog today for this

**Comment by mpiannucci** [comment]
These are now live on the beta site

**Comment by cpaternostro** [comment]
Thanks,
I am right here on the Columbia River right now.  Just made a decision to
delay the deployment on a buoy because the currents are too fast.  Coming
back to the buoy in 3 hours based on this data.

https://dev.oceansmap.com/ott-coops/?permalink=N4IgtghgDgQjD2APEAuUB9Azgd1aANgHYDmqAtAIwBMAzAHQ0UUAsrAnFQOwCsADAGxsAHABoQ+CABdUzfnQo0qvTrzaNunIZwoBfMekIBTPOJLlq9KoO5s1NIbK6cxE6SlnzmQ-s2XUKbLICOnrg0ADKkgCe+MZoIACWACaoIBAATgDGAOIJmAAq8FDwxOnQABYJmSBihBBgcSCFxaUVVTUgkuUArmAARnUJ+KnlkpJQmCgA9FOYhukAbvN0GZnEefCE+AlGdJnwYFOr65hT6YaYkrPzC1UXUwDq8On4SejN8OgAstBTP1DhG7zKaSIaGKa8CEQjqXGJxUBLdKYBKbVCiECYeDdLIXEySIolMpQSrVeLRKCNMqXeYdUGxTCoADaIFG40mMzmi2Wxw2Wx2hj2ByOWROZwuV05t0y9yeLzeH2+v3+gK56RBYKmwAAXjpNVFdcBEDoQABdMR0wzhBJauJUbj8MRSSTpBJ9bqg1EoEAAUUwLpEAAJshkwDtA9lvTAAMIAeUDADkYwBBJMB+PZAAiUcDEEISQD8C68wD+0Iztd7ueDJCLggUXmDJQjNAyVS+JaRJJtKiFNSVMkNLEmOx0rbBNaxPaYlDhC18AOqF404giDnC5QVCoOhNNZA2DAmEBYx2xEboEI8Ew6Ey53gADMrzQ3plsecy2eMdFYqlkTa3hl0ngbAGTEfZ8GeAAFCBYjGRo+gyPpTjmABHMhsnOKJq1CF90jfSR-nyBIGmpKBUiUTcyGUSgaHyCh+BQXheAY3g6EY3gAC0OkgKBCOIgcoAAJVzYg4mZciqEozhKAofJeGYZjmNYxjOLEcTJMobhZPkxjFLYzizRAHC8IzQwoC6RcxG6QgEkkcJMIHMBUiIikXWgmFDFiTIByScJpTqF14AAGTrBsmQMzF0m84L63SABJDNG2ZSAXVBBoyEMQhqlqS9r1vB90Cfa9XwyyQQMM+AIEubYjAZAykikCAowa8DiAAMSGAd0hMS4XTML0wO6EBQngRCbikFFCCgsoGk6xKQAvK8b0Me9H2fYr31NMQRslcbNijeBwKREwFty5b8sKoySsbFlMHwAAKBxAwoRiAFJAx8F6AEohuXKAo22TIAGtvSWMsTCIYhgrcAg+soWg6CoIRhE3O1lE4ewqFrNwPBYVgqGR-h+Do-gaFCYodmhkBkBQbgtDEKJUDo7hQjvQwpGxXEmx3HQgA


--

Chris Paternostro

https://tidesandcurrents.noaa.gov/
