### ISSUE TITLE
Inconsistent Directional Values

### ISSUE THREAD

**Issue by jamesdoyle21** [asascience/ott-coops#512]
Some layers have 360 degrees facing north while others have 180 facing north. For the models this isn't great, but at least you can see on the map the direction it is headed. When the user selects a observation station and the only reference for direction is a degree value, I have no idea what that means because OceansMap uses different directional headings.

**Comment by jamesdoyle21** [comment]
173 pointed South

![image](https://user-images.githubusercontent.com/82955395/179076566-bcd12cab-f94b-46aa-a300-90318217826a.png)

**Comment by jamesdoyle21** [comment]
185 pointed North

![image](https://user-images.githubusercontent.com/82955395/179076915-e1a7a4fe-74ca-4b4c-a010-5b3f6ee6840e.png)

**Comment by jamesdoyle21** [comment]
Now I don't know what this means

![image](https://user-images.githubusercontent.com/82955395/179077151-f37fc94b-e581-4765-8733-58d0cc9a5ecb.png)

**Comment by mpiannucci** [comment]
Yes, notice the "towards" in the unit label. Some datasets are direction towards, some are direction from. So when it says towards in the unit label it means the direction its heading. Otherwise it means the direction it is coming from. its what we get back from ncwms for the timeseries. If you check OM1 it should show the same thing. 

The last one you posted im not sure what the confusion is, the scatter plot says the direction is 84 degrees

**Comment by jamesdoyle21** [comment]
So that last one would be coming from 84 degrees because it doesn't have the term "towards" in front? So moving from east to west? I guess that is fine, it is just a lot to piece together without an arrow. We should probably explain the towards/from thing somewhere.

**Comment by mpiannucci** [comment]
![Image](https://user-images.githubusercontent.com/1832671/179535224-1356b323-ef3a-4cf3-9438-787aef9ef3b8.png)

**Comment by mpiannucci** [comment]
Deleted
