### ISSUE TITLE
Wind Direction Validation Results do not fit on iPhone Screen

### ISSUE THREAD

**Issue by jamesdoyle21** [asascience/ott-coops#521]
From Jeff, "Wind direction Validation results on iPhone do not fit screen- see attached"

![33052 (002)](https://user-images.githubusercontent.com/82955395/180788875-258882e3-d7f9-40f1-bf4e-049e6368e824.jpg)

**Comment by jamesdoyle21** [comment]
This does fit fine on my android though.

**Comment by kvmartin001** [comment]
I think this is the mobile browser automatically zooming in about 10% when the user taps the comparison dropdown.
Safari does this when an element's font size is smaller than a certain threshold.

It's apparently a common problem - I'll try adding `maximum-scale=1` to the viewport meta tag since that seems to be the latest solution. https://techstacker.com/html-disable-auto-zoom-input-element-ios/

**Comment by jamesdoyle21** [comment]
@kvmartin001 you tested this and it is all set? It always looked fine on my android

**Comment by kvmartin001** [comment]
@jamesdoyle21 Yep, it's in the client demo and I just checked on iOS safari and Chrome - it fixes the issue and you can still manually scroll the browser on both
