### ISSUE TITLE
Leave a Gap in Plot When There is a Gap in the Data

### ISSUE THREAD

**Issue by jamesdoyle21** [asascience/ott-coops#68]

**Comment by nguyandy** [comment]
@mpiannucci @jamesdoyle21, do you guys know off the top of your head which layers have the gap in the plots?
Can't seem to find one in the new ott catalog.

**Comment by mpiannucci** [comment]
It was the current data from lewes launch

**Comment by cpaternostro** [comment]
With CO-OPS Stations, for the Sea Water Speed plots:
1. t02010 had a gap from 8/16 0005 to 8/16 1323  But this station is not available on MARACOOS OceansMap, that seems like a bug
2. cb0402 had a gap from 2021-08-12 21:51:00 to 2021-08-13 03:45:00 - straight line can be seen connecting the points bracketing the gap
3. sn0101 had a small gap on 7/19 20:00 to 7/20 02:25 where the straight line gap exists on the water speed line plot.  However the much larger gap from 7/22 to 8/12 does not have the straight line filling the gap because it is so big.
4.  Water level and all line plot data will have the same problem.  Note the Sea Water Velocity to Direction does not exhibit this problem because they are points.

**Comment by jamesdoyle21** [comment]
2.
![image](https://user-images.githubusercontent.com/82955395/129900940-8f71e07f-0031-4848-b147-8251efd3fdfd.png)

**Comment by jamesdoyle21** [comment]
3.
![image](https://user-images.githubusercontent.com/82955395/129901444-ff296e76-007a-4cd4-bd2a-954d552271b4.png)

**Comment by jamesdoyle21** [comment]
@nguyandy

**Comment by mpiannucci** [comment]
So the way we can calculate this is similar to the way the validation tool. we can should find the median difference between each data point and if the reported time is too high over that threshold then it is treated as a separate line and should not be connected. The hardest part is than putting it on the plot like that so the legends arent messed up

**Comment by cpaternostro** [comment]
How does it look if you were just to plot the time series as points instead
of lines?

--

Chris Paternostro

https://tidesandcurrents.noaa.gov/

(w) 240-533-0587

**Comment by jamesdoyle21** [comment]
If there are enough data points, the plot may look better without lines like Chris mentioned. Thoughts here @mpiannucci ?

**Comment by mpiannucci** [comment]
cc @kvmartin001

**Comment by nguyandy** [comment]
fyi:
https://github.com/asascience/OceansMap/blob/master/oceansmap/static/js/views/HighchartsView.js#L844

**Comment by kvmartin001** [comment]
I have this working with a similar function to the OM1 code, but there are two problems with it currently.
1. My function is way too slow. It takes about 15 seconds to process the new dataset and display it.
2. It's tough to determine how much time should be considered a gap. Coops station cb0402 updates every 300-700 seconds, but frequently has gaps of 1000ish seconds. If I set the cutoff to be 2x the average difference, the plot is just full of holes.

Here is cb0402 with an 8x average difference cutoff.

![image](https://user-images.githubusercontent.com/56608780/150859965-3b311f8a-24a5-49b4-9a71-c55cbd55000d.png)

Looks like OM1 allows the cutoff value to be configured.

**Comment by cpaternostro** [comment]
All CO-OPS real-time stations should be reporting at 360 seconds.  6
minutes is our standard.


--

Chris Paternostro

https://tidesandcurrents.noaa.gov/

(w) 240-533-0587
